### ISSUE TITLE
Is someone getting this like issue

### ISSUE THREAD

**Issue by viradhanus** [scorelab/TrackPal#56]
Are there any one facing similar issue with new updates? Please help 😊 

![Screenshot (82)](https://user-images.githubusercontent.com/59219626/73660994-49dadf00-46bf-11ea-9e55-5e0841a22633.png)

**Comment by viradhanus** [comment]
I tried using ubuntu again and this was the result

![Screenshot from 2020-02-04 11-23-56](https://user-images.githubusercontent.com/59219626/73718563-e09caf80-4742-11ea-82b6-1d9c418adaf4.png)

Then I tried `react-native install react-native-fbsdk@0.8.0`  but it keeps throwing errors such as

![Screenshot from 2020-02-04 11-34-13](https://user-images.githubusercontent.com/59219626/73718903-cfa06e00-4743-11ea-9ca0-7a55123b2c94.png)

**Comment by shehand** [comment]
The issue with this is the missing of jetifying the project after adding the androidX support.
