### ISSUE TITLE
Build fails due to following error

### ISSUE THREAD

**Issue by kasunara** [scorelab/TrackPal#59]
Hi,

When I execute "react-native run-android" the build getting failed with following error messages

![image](https://user-images.githubusercontent.com/64719583/81095880-3ee45480-8f23-11ea-8e35-a66a34902b54.png)

**Comment by shehand** [comment]
@kasunara Can you add the full error message?

**Comment by r0ushann** [comment]
is this issue still open?
or else you can close it! @kasunara 
thank you.
